FROM ruby:3.2.2

WORKDIR /app

RUN curl -fsSL https://deb.nodesource.com/setup_24.x | bash -
RUN apt-get install -y nodejs
RUN npm uninstall yarn -g
RUN npm install yarn -g -y

RUN yarn cache clean && yarn add react react-dom
RUN yarn add @supabase/supabase-js

RUN apt-get update
RUN apt-get install -y vim

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY Gemfile Gemfile.lock /app/
RUN bundle install

COPY . /app/